#!/bin/bash
#SBATCH -J test_GGM_50-0-1-0
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH -o test_GGM_50-0-1-0.out 
#SBATCH -e test_GGM_50-0-1-0.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

module load anaconda3
module load cuda/11.1.1
conda activate myenv

cd ${PROJECT}/DynGRN/test/scripts_GGM

# 1st argument: use kendall-tau or not, True (0) or False (1)
# 2nd argument: interval 5 (0), 25 (1)
# 3rd argument: seed, 0,1,2
seed=0
interval=1
kt=0
python test_GGM_50.py ${kt} ${interval} ${seed}
