#!/bin/bash
#SBATCH -J test_mESC_kt-0
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH -o test_mESC_kt-0.out 
#SBATCH -e test_mESC_kt-0.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

module load anaconda3
module load cuda/11.1.1
conda activate myenv

# RUN GENIE3 & ADMM
cd /ocean/projects/cis210014p/ziqi/DynGRN/test/scripts_mESC

bandwidth=0
truncate_param=0
python test_mESC_kt.py ${bandwidth} ${truncate_param}

