#!/bin/bash
#SBATCH -J test_GGM_200-0010
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH -o test_GGM_200-0010.out 
#SBATCH -e test_GGM_200-0010.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

module load anaconda3
module load cuda/11.1.1
conda activate myenv

cd ${PROJECT}/DynGRN/test/scripts_GGM_bifur_v3

# 1st argument: use kendall-tau or not, True (0) or False (1)
# 2nd argument: interval 5 (0), 25 (1)
# 3rd argument: seed, 0,1,2
kt=0
interval=0
seed=1
bandwidth=0
truncate_param=0

python test_GGM_200.py ${kt} ${interval} ${seed} ${bandwidth} ${truncate_param}
