#!/bin/bash
#SBATCH -J test_THP-1
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH -o test_THP-1.out 
#SBATCH -e test_THP-1.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

module load anaconda3
module load cuda/11.1.1
conda activate myenv

# RUN GENIE3 & ADMM
cd /ocean/projects/cis210014p/ziqi/DynGRN/test/scripts_THP-1
python test_THP-1.py

# # RUN SCODE
# cd /ocean/projects/cis210014p/ziqi/DynGRN/SCODE
# data_dir=../data/COUNTS-THP-1
# result_dir=../test/results_THP-1/SCODE
# ruby run_R.rb ${data_dir}/expr.txt ${data_dir}/dpt_time.txt ${result_dir} 45 4 960 100 5
