#!/bin/bash
#SBATCH -J test_THP-1-kt-13
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH -o test_THP-1-kt-13.out 
#SBATCH -e test_THP-1-kt-13.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

module load anaconda3
module load cuda/11.1.1
conda activate myenv

# RUN GENIE3 & ADMM
cd /ocean/projects/cis210014p/ziqi/DynGRN/test/scripts_THP-1

bandwidth=4
truncate_param=1
python test_THP-1_kt.py ${bandwidth} ${truncate_param}

