#!/bin/bash
#SBATCH -J test_GGM2_copy2
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH --ntasks-per-node=64
#SBATCH --mem=125GB
#SBATCH -t 24:00:00
#SBATCH -o test_GGM2_copy2.out 
#SBATCH -e test_GGM2_copy2.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

# type 'man sbatch' for more information and options
# this job will ask for 1 full RM node (8 cores) for 5 hours
# this job would potentially charge 640 RM SUs

module load anaconda3
conda activate myenv

# move to working directory
# this job assumes:
# - all input data is stored in this directory
# - all output should be stored in this directory
# - please note that groupname should be replaced by your groupname
# - username should be replaced by your username
# - path-to-directory should be replaced by the path to your directory where the executable is

cd /ocean/projects/cis210014p/ziqi/DynGRN/test/scripts2

# run pre-compiled program which is already in your project space
python test_GGM2_copy2.py