#!/bin/bash
#SBATCH -J test_GGM_50
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH -o test_GGM_50.out 
#SBATCH -e test_GGM_50.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

module load anaconda3
module load cuda/11.1.1
conda activate myenv

cd ${PROJECT}/DynGRN/test/scripts_GGM_bifur_v2

for seed in 0 1 2 3 4
do
    python test_GGM_50.py sergio ${seed}
done
