#PBS -N test_scode
#PBS -q hive-himem
#PBS -l nodes=1:ppn=4
#PBS -l walltime=10:20:00
#PBS -j oe
#PBS -o test_scode.out
#PBS -m abe                            
#PBS -M zzhang834@gatech.edu
#PBS -t 0,1,2,3,4


cd /storage/home/hhive1/zzhang834/data/DynGRN/SCODE
module load ruby

data_dir=../data/GGM_bifurcate
result_dir=../test/results_GGM

##############################################################################################

# Static

##############################################################################################

# Sergio graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/sim_time.txt ${result_dir}/${sub_folder}/SCODE_truet $ngenes 4 1000 100 5
        done
    done
done

# Random graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/sim_time.txt ${result_dir}/${sub_folder}/SCODE_truet $ngenes 4 1000 100 5
        done
    done
done

# Sergio graph init, using dpt
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/dpt_time.txt ${result_dir}/${sub_folder}/SCODE_dpt $ngenes 4 1000 100 5
        done
    done
done

# Random graph init, using dpt
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/dpt_time.txt ${result_dir}/${sub_folder}/SCODE_dpt $ngenes 4 1000 100 5
        done
    done
done

##############################################################################################

# Dynamic

##############################################################################################

# Sergio graph init using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/sim_time_${i}.txt ${result_dir}/${sub_folder}/SCODE_truet/${i} $ngenes 4 100 100 5
            done
        done
    done
done

# Random graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/sim_time_${i}.txt ${result_dir}/${sub_folder}/SCODE_truet/${i} $ngenes 4 100 100 5
            done
        done
    done
done

# Sergio graph init, using dpt
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/dpt_time_${i}.txt ${result_dir}/${sub_folder}/SCODE_dpt/${i} $ngenes 4 100 100 5
            done
        done
    done
done

# Random graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in ${PBS_ARRAYID}
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/dpt_time_${i}.txt ${result_dir}/${sub_folder}/SCODE_dpt/${i} $ngenes 4 100 100 5
            done
        done
    done
done


