#!/bin/bash
#SBATCH -J test_SCODE
#SBATCH -N 1
#SBATCH -p RM-shared
#SBATCH --ntasks-per-node=8
#SBATCH -t 8:00:00
#SBATCH -o test_SCODE.out 
#SBATCH -e test_SCODE.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

cd /ocean/projects/cis210014p/ziqi/DynGRN/SCODE

data_dir=../data/GGM_bifurcate
result_dir=../test/results_GGM

##############################################################################################

# Static

##############################################################################################

# Sergio graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/sim_time.txt ${result_dir}/${sub_folder}/SCODE_truet $ngenes 4 1000 100 5
        done
    done
done

# Random graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/sim_time.txt ${result_dir}/${sub_folder}/SCODE_truet $ngenes 4 1000 100 5
        done
    done
done

# Sergio graph init, using dpt
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/dpt_time.txt ${result_dir}/${sub_folder}/SCODE_dpt $ngenes 4 1000 100 5
        done
    done
done

# Random graph init, using dpt
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
            sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
            mkdir -p ${result_dir}/${sub_folder}
            echo $sub_folder
            ruby run_R.rb ${data_dir}/${data_sub_folder}/expr.txt ${data_dir}/${data_sub_folder}/dpt_time.txt ${result_dir}/${sub_folder}/SCODE_dpt $ngenes 4 1000 100 5
        done
    done
done

##############################################################################################

# Dynamic

##############################################################################################

# Sergio graph init using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/simtime_${i}.txt ${result_dir}/${sub_folder}/SCODE_truet/${i} $ngenes 4 100 100 5
            done
        done
    done
done

# Random graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/simtime_${i}.txt ${result_dir}/${sub_folder}/SCODE_truet/${i} $ngenes 4 100 100 5
            done
        done
    done
done

# Sergio graph init, using dpt
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_sergio
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_sergio
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/dpttime_${i}.txt ${result_dir}/${sub_folder}/SCODE_dpt/${i} $ngenes 4 100 100 5
            done
        done
    done
done

# Random graph init, using true t
for ngenes in 50 200
do
    for interval in 5 25 100
    do
        for seed in 0 1 2 3 4
        do
            for i in {0..9}
            do
                data_sub_folder=ntimes_1000_interval_${interval}_ngenes_${ngenes}_${seed}_random
                sub_folder=bifur_1000_${interval}_${ngenes}_${seed}_random
                mkdir -p ${result_dir}/${sub_folder}
                echo $sub_folder
                ruby run_R.rb ${data_dir}/${data_sub_folder}/expr_${i}.txt ${data_dir}/${data_sub_folder}/dpttime_${i}.txt ${result_dir}/${sub_folder}/SCODE_dpt/${i} $ngenes 4 100 100 5
            done
        done
    done
done


