#!/bin/bash
#SBATCH -J test_GGM_200
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:1
#SBATCH -t 12:00:00
#SBATCH -o test_GGM_200.out 
#SBATCH -e test_GGM_200.err
#SBATCH --mail-user=zzhang834@gatech.edu
#SBATCH --mail-type=ALL

module load anaconda3
module load cuda/11.1.1
conda activate myenv

cd ${PROJECT}/DynGRN/test/scripts_GGM_bifur_v2

for seed in 0 1 2 3 4
do
    for bandwidth in 0.1 1 10
    do
        for truncate_param in 15 30 100
        do
            python test_GGM_200_1.py sergio ${seed} ${bandwidth} ${truncate_param}
        done
    done

    for bandwidth in 0.1 1 10
    do
        for truncate_param in 15 30 100
        do
            python test_GGM_200_2.py sergio ${seed} ${bandwidth} ${truncate_param}
        done
    done

    for bandwidth in 0.1 1 10
    do
        for truncate_param in 15 30 100
        do
            python test_GGM_200_3.py sergio ${seed} ${bandwidth} ${truncate_param}
        done
    done

done