#PBS -N test_GGM200_1
#PBS -q hive-gpu
#PBS -l nodes=1:ppn=4:gpus=1
#PBS -l walltime=20:20:00
#PBS -j oe
#PBS -o test_GGM200_1.out
#PBS -m abe                            
#PBS -M zzhang834@gatech.edu
#PBS -t 0,1,2,3,4

cd $PBS_O_WORKDIR
module load anaconda3
conda activate myenv

bandwidth=0.1
truncate_param=15
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}

bandwidth=0.1
truncate_param=30
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}

bandwidth=0.1
truncate_param=100
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}


bandwidth=1
truncate_param=15
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}

bandwidth=1
truncate_param=30
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}

bandwidth=1
truncate_param=100
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}


bandwidth=10
truncate_param=15
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}

bandwidth=10
truncate_param=30
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}

bandwidth=10
truncate_param=100
python test_GGM_200_1.py sergio ${PBS_ARRAYID} ${bandwidth} ${truncate_param}